
### Discord ####
# The token used to log into discord
discordToken = "<DISCORD_TOKEN>"
# Whether to use webhooks for creating messages
useWebhooks = false

# Default Channel topic
useDefaultChannelTopic = true
defaultChannelTopic = "{nPlayers}/{maxPlayers} Players. Running at {tps}t/s | {mspt}ms."

# The url used to get the webhook avatar for minecraft players
# Variables:
#   username: the username of the player
#   uuid: the uuid of the player
minecraftAvatarProviderUrl = "https://api.mineatar.io/head/{uuid}?scale=16"
# The url used to get the webhook avatar for hytale players
# Variables:
#   username: the username of the player
#   id: the id of the player
hytaleAvatarProviderUrl = "https://hyvatar.io/render/{username}?size=128&rotate=22"

[formats]
# The format to be used when creating a message
# Variables:
#  Shared:
#   author: the name of the author
#   content: the message content
#  Spefici:
#   prefix: luckperms prefix
#   suffix: luckperms suffix
toDiscordChatFormat = "{prefix}{author}{suffix}» {content}"
#  Specific
#   role: the discord role (if the user doesn't have a role, this will be "Discord")
toMinecraftChatFormat = "[{role}] {author} » {content}"
toHytaleChatFormat = "[{role}] {author} » {content}"
# The format to be used when a player joins or leaves
# Variables:
#   player: the name of the player
#   prefix: luckperms prefix
#   suffix: luckperms suffix
playerJoinedMessage = "{prefix}{player}{suffix} joined the game."
playerLeftMessage = "{prefix}{player}{suffix} left the game."

# Variables:
#   player, prefix, suffix
#   deathMessage: the server-provided death message
playerDeathMessage = "{deathMessage}"

# Variables:
#   player, prefix, suffix
#   name, description: advancement name and description
mcTaskAdvancementMessage = "{prefix}{player}{suffix} completed the task `{name}`: {description}"
mcGoalAdvancementMessage = "{prefix}{player}{suffix} achieved the goal `{name}`: {description}"
mcChallengeAdvancementMessage = "{prefix}{player}{suffix} completed the challenge `{name}`: {description}"

# The message to send when the server starts and stops
serverStartedMessage = "Server Started."
serverStoppedMessage  = "Server Stopped."

# Example channel configuration (the default channel is required)
[[channels]]
# Channel name (this is used internally and mapped to minecraft/hytale channel/team names)
channelName = "default"
# Discord channel id
channelId = 1111111
# This is the discord webhook id, can be removed if not using webhooks
webhookId = 0000
# This is the discord webhook token, can be removed if not using webhooks
webhookToken = ""

# Example staff channel
[[channels]]
channelName = "staff"
channelId = 222222