[versions]
kotlin = "2.3.21"
shadow = "9.4.1"
slf4j = "2.0.17"
ktoml = "0.7.1"
kyori = "5.0.0"
luckperms = "5.4"
kord = "0.18.1"

[libraries]
slf4j-simple = { module="org.slf4j:slf4j-simple", version.ref="slf4j" }
ktoml-core = { module="com.akuleshov7:ktoml-core", version.ref="ktoml" }
ktoml-file = { module="com.akuleshov7:ktoml-file", version.ref="ktoml"}
kord-core = { module="dev.kord:kord-core", version.ref="kord" }
kyori-api = { module="net.kyori:adventure-api", version.ref = "kyori" }
luckperms = { module="net.luckperms:api", version.ref="luckperms" }

[plugins]
kotlin-jvm = { id="org.jetbrains.kotlin.jvm", version.ref="kotlin" }
kotlin-plugin-serialization = { id="org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin" }
shadow = { id="com.gradleup.shadow", version.ref="shadow" }