plugins {
    id("java-library")
    id("maven-publish")
    id("net.neoforged.moddev")
    alias(libs.plugins.kotlin.jvm)
}

// Fetching properties from gradle.properties safely using delegates
val modVersion = rootProject.version
val modGroupId: String by project
val modId: String by project
val neoVersion: String by project

// Properties needed for the metadata task
val minecraftVersion: String by rootProject
val minecraftVersionRange: String by project
val neoVersionRange: String by project
val loaderVersionRange: String by project
val modName: String by project
val modLicense: String by project
val modAuthors: String by project
val modDescription: String by project

project.version = rootProject.version
group = modGroupId
base.archivesName = project.property("archives_base_name") as String

repositories {
    mavenLocal()
    maven {
        name = "Kotlin for Forge"
        url = uri("https://thedarkcolour.github.io/KotlinForForge/")
        content {
            includeGroup("thedarkcolour")
        }
    }
    maven("https://snapshots.kord.dev")
}

kotlin {
    compilerOptions {
        freeCompilerArgs.apply {
            add("-Xreturn-value-checker=full")
            add("-Xwarning-level=RETURN_VALUE_NOT_USED:error")
        }
    }
}

java.toolchain.languageVersion.set(JavaLanguageVersion.of(25))
kotlin.jvmToolchain(25)

neoForge {
    // Specify the version of NeoForge to use.
    version = neoVersion

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers.add("src/main/resources/META-INF/accesstransformer.cfg")

    // Default run configurations.
    runs {
        create("client") {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            clientData()

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            systemProperty("forge.logging.markers", "REGISTRIES")

            // Recommended logging level for the console
            logLevel.set(org.slf4j.event.Level.DEBUG)
        }
    }

    mods {
        // define mod <-> source bindings
        create(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.get().resources.srcDir("src/generated/resources")

dependencies {
    implementation("thedarkcolour:kotlinforforge-neoforge:6.2.0")
    jarJar(implementation(project(path = ":dforblock-core", configuration = "shadow"))) { }
    jarJar(implementation("net.kyori:adventure-platform-neoforge:${project.property("kyori_adventure_neoforge_version")}")) { }
    compileOnly(libs.kotlin.logging)
    compileOnly(libs.json5)

    // Example mod dependency with JEI
    // compileOnly("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    // compileOnly("mezz.jei:jei-${mc_version}-forge-api:${jei_version}")
    // runtimeOnly("mezz.jei:jei-${mc_version}-forge:${jei_version}")
}

tasks.processResources {
    from(rootProject.file("config/core.json5"))
    from(rootProject.file("config/channels.json5"))
    from(rootProject.file("config/permissions.json5"))
    from(rootProject.file("config/messages.json5"))
}

// This block of code expands all declared replace properties in the specified resource targets.
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    description = modDescription
    val replaceProperties = mapOf(
        "minecraft_version" to minecraftVersion,
        "minecraft_version_range" to minecraftVersionRange,
        "neo_version" to neoVersion,
        "neo_version_range" to neoVersionRange,
        "loader_version_range" to loaderVersionRange,
        "mod_id" to modId,
        "mod_name" to modName,
        "mod_license" to modLicense,
        "mod_version" to modVersion,
        "mod_authors" to modAuthors,
        "mod_description" to modDescription
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

// Include the output of "generateModMetadata" as an input directory for the build
sourceSets.main.get().resources.srcDir(generateModMetadata)
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("file://${project.projectDir}/repo")
        }
    }
}